rofi wallpaper: rewrite script

diff --git a/bin/bin/random-wallpaper b/bin/bin/random-wallpaper
--- a/bin/bin/random-wallpaper
+++ b/bin/bin/random-wallpaper
@@ -1,41 +1,58 @@
 #!/bin/bash
 
+# Define a help message
+_help_message() {
+    echo "ERROR. Must pass a single argument."
+    echo "Examples of valid arguments:"
+    echo "-r - random from all"
+    echo "-l - random from latest"
+    echo "-v - random from most viewed"
+    echo "-t - random from toplist"
+    echo "-f - random from favorites"
+}
+
+# Show the help message if arguments are not equal to one.
+[ "$#" -eq 1 ] || {
+    _help_message
+    exit 1
+}
+
 # Name for your wallpaper image
 img="wallpaper.jpg"
 
 # Image folder location
-img_folder="$HOME/Pictures"
+img_dir="$HOME/Pictures"
 
 # Set the resolution
 # All: Do not include for all
 # standard:
-#	800x600 1024x768 1280x960 1280x1024 1400x1050 1600x1200 2560x2048
+#   800x600 1024x768 1280x960 1280x1024 1400x1050 1600x1200 2560x2048
 # widescreen:
-#	1024x600 1280x800 1366x768 1440x900 1600x900 1680x1050 1920x1080
-#	1920x1200 2560x1440 2560x1600
-# atleast=1920x1080
+#   1024x600 1280x800 1366x768 1440x900 1600x900 1680x1050 1920x1080
+#   1920x1200 2560x1440 2560x1600
+atleast=1920x1080
 
 # Set the purity filter setting
-# SFW			    = 100
-# Sketchy			= 010
-# Both				= 110
+# SFW               = 100
+# Sketchy           = 010
+# Both              = 110
 purity=100
 
 # Set the category
-# General		        = 100
-# Anime                 = 010
-# People            	= 001
+# General           = 100
+# Anime             = 010
+# People            = 001
 # NOTE: Can combine them
-categories=111
+categories=100
 
 # Set the aspect ratio of the image
-# All				= Do not include for all
-# 4:3				= 4x3
-# 5:4				= 5x4
-# 16.9				= 16x9
-# 16:10				= 16x10
-# 32:9  			= 32x9
-# 48:9				= 48x9
+# All               = Do not include for all
+# 4:3               = 4x3
+# 5:4               = 5x4
+# 16.9              = 16x9
+# 16:10             = 16x10
+# 32:9              = 32x9
+# 48:9              = 48x9
 # NOTE: Can combine them by seperating with ,
 ratios=16x9
 
@@ -48,34 +65,45 @@ ratios=16x9
 # #cccc33 #ff9900 #ff6600 #cc6633 #996633 #663300
 # #000000 #999999 #cccccc #ffffff #424153
 
-#colors=cccc33
+# colors=cccc33
 
 # Set the site address
 site="wallhaven.cc"
 
 # Combine the two above
-wallpaper="$img_folder/$img"
+wallpaper="$img_dir/$img"
 
 # Address for the wallpaper website along with all of the selected options
-wallpaper_url="https://$site/search?categories=$categories&purity=$purity&sorting=random&order=desc"
+wallpaper_url="https://$site/search?categories=$categories&purity=$purity&order=desc"
 
-if [ -n "$colors" ]; then
-    wallpaper_url+="&colors=$colors"
-fi
+[[ -n "$colors" ]] && wallpaper_url+="&colors=$colors"
 
-if [ -n "$ratios" ]; then
-    wallpaper_url+="&ratios=$ratios"
-fi
+[[ -n "$ratios" ]] && wallpaper_url+="&ratios=$ratios"
 
-if [ -n "$atleast" ]; then
-    wallpaper_url+="&atleast=$atleast"
-fi
+[[ -n "$atleast" ]] && wallpaper_url+="&atleast=$atleast"
+
+rand_page=$(($RANDOM % 20 + 1))
+
+case "$1" in
+"-l") wallpaper_url+="&sorting=date_added&page=$rand_page" ;;
+"-v") wallpaper_url+="&sorting=views&page=$rand_page" ;;
+"-t") wallpaper_url+="&sorting=toplist&page=$rand_page" ;;
+"-f") wallpaper_url+="&sorting=favorites&page=$rand_page" ;;
+*) wallpaper_url+="&sorting=random" ;;
+esac
+
+# Randomly selected images
+rand_pics_urls=($(curl -s "$wallpaper_url" | grep -oE 'https://'$site'/w/[[:alnum:]]{6}'))
 
 # Randomly selected image
-rand_pic_url=$(curl -s "$wallpaper_url" | grep -oP '<a class="preview" href="https://'$site'/w/(.*)"' | head -1 | cut -d "\"" -f 4)
+rand_pic_url=${rand_pics_urls[$RANDOM % ${#rand_pics_urls[@]}]}
 
 # Parse out the image url
-rand_pic=$(curl -s $rand_pic_url | grep -oP 'src="https://w.'$site'/full/(.*)' | cut -d "\"" -f 2)
+rand_pic=$(curl -s $rand_pic_url | grep -oE 'https://w.'$site'/full/[[:alnum:]]{2}/wallhaven-[[:alnum:]]{6}\.(jpg|png)')
 
 # Download it
 curl -s $rand_pic -o $wallpaper
+
+# Convert to jpg if the image format is png
+type=$(file $wallpaper | awk '{print $2}')
+[[ "$type" == "PNG" ]] && convert "$wallpaper" "$wallpaper"
